### ISSUE TITLE
Sinon.fakeTimer doesn't handle the result of moment.format('x')

### ISSUE THREAD

**Issue by tutuca** [cjohansen/Sinon.JS#700] opened 2015-03-03 18:05 UTC
Fiddle here http://jsfiddle.net/tutuca/e3s21Lab/, although it fails to run.
I have packaged the minimal case that you can run ([download](https://dl.dropboxusercontent.com/u/163405/tiempo.tar.gz))

So, the gist of it is that `moment().format('x')` returns milliseconds from UNIX epoch but `sinon.fakeTimer` fails with a non obvious error `TypeError: Cannot set property 'hadOwnProperty' of undefined`

    describe("Test sinon.fakeTimes with Moment.js", function() {
        var today, tomorrow, ticks, clock;
        beforeEach(function(){
            // get milliseconds since UNIX epoch for this date.
            ticks = parseInt(moment('01/15/2015').format('x'));
            // set the timers to start at expected time.
            clock = sinon.useFakeTimers(ticks);

        });
        afterEach(function(){
            clock.restore();
        });
        it("date is set in some arbitrary time.", function() {
            today = new moment();
            tomorrow = today.add(1, 'days');
            expect(tomorrow.format('MM/DD/YYYY')).toBe('01/16/2015');
        });
    });

See how I needed to wrap the time with `parseInt`? 
This error is not descriptive and is very misleading, even though moment is probably to blame we should handle the situation in a more elegant way.

Opinions?

**Comment by mroderick** [comment] 2015-03-05 06:05
That looks like an interesting scenario, thank you for reporting this.

I'll take a closer look when I get a chance to.

Have you managed to boil down a failing test for `moment`? The error should also be reported to that project.

**Comment by freethejazz** [comment] 2015-03-09 02:47
This is not a bug, but expected behavior. `moment().format('x')` returns ms from epoch as a string, but `sinon.fakeTimer` expects a number. If you want ms from the epoch as a number, use `moment().valueOf()` or `+moment()` instead.

http://momentjs.com/docs/#/displaying/unix-offset/

@mroderick I believe this should be closed as it is not actually a bug.

**Comment by willmorgan** [comment] 2015-07-21 10:56
It would be nice if Sinon complained about the type, or at least tried to coerce it.

**Comment by cjohansen** [comment] 2015-07-21 15:56
This is not Sinon's fault, but I agree that the error could be better. A pull request that improves [this function](https://github.com/sinonjs/lolex/blob/master/src/lolex.js#L71) would be most welcome.

**Closed by cjohansen** 2015-07-21 15:56 UTC
Labels: 1.x, Bug
